name: config-encryption
# -----METADATA FOR MAT-------
mat_sno: 4
mat_category: cloud-mandatory
mat_title: Usage of Configuration Encryption
mat_description: Use of encrypted sections is problematic in cloud environments. Configurations should be externalized as environment variables instead of encrypting them in configuration file.
mat_group: DOTNET_CLOUD_CONFIG
mat_criticality: Low
# -----------------------------
filetype: config$
target: file
type: xpath
advice: Use of encrypted sections is problematic in cloud environments. Configurations should be externalized as environment variables instead of encrypting them in configuration file.
effort: 300
category: security
tags:
- value: security
- value: encryption
patterns:
  - value: //*[@configProtectionProvider][1]
