name: dotnet-iis_module-IpSecurity
# -----METADATA FOR MAT-------
mat_sno: 48
mat_category: .NETCORE PORTABILITY
mat_title: IP Security IIS Module
mat_description: Windows and IIS server dependency. Not supported in .netCore targeting linux.
mat_group: IIS MODULE
mat_criticality: Medium
# -----------------------------
filetype: config$
target: file
type: xpath
advice: Windows and IIS server dependency. Not supported in .netCore targeting linux.
patterns:
- value: /configuration/system.webServer/security/ipSecurity
readiness: 9
effort: 0
category: unsupported-iis-module
tags:
- value: iis-module
#- <configuration><system.webServer><security><ipSecurity
# Mostly a challenge if moving to .NetCore