#qc1
name: config-encryption
filetype: config$
target: file
type: xpath
advice: Use of encrypted sections is problematic in cloud environments
effort: 300
category: Security
tags:
- value: Protection-Provider
patterns:
  - value: //*[@configProtectionProvider][1]
