#qc1
name: config-sessionState
filetype: config$
target: line
type: contains
advice: App should be executed as a stateless process
readiness: 2
effort: 500
category: stateful
tags:
  - value: stateful
  - value: TAS
patterns:
  - value: mode="InProc"
  - value: mode="StateServer"
## mode="InProc"
## mode="StateServer"
