#qc1
name: dotnet-ISAPI-Filters-config
filetype: config$
target: line
type: contains
advice: Refer to platform documentation
category: Unsupported IIS modules
effort: 1000
readiness: 0
patterns:
- value: <isapiFilters
## <isapiFilters
