name: dotnet-security
filetype: (cs$|vb$)
target: line
type: contains
advice: Relying on Windows certificate stores is problematic in a cloud environment.
readiness: 10
effort: 3
category: Security
tags:
- value: Security
patterns:
- value: X509Store
  tag: X509Store
## X509Store
