name: dotnet-file-based-config
filetype: cs
target: line
type: contains
advice: Externalize configuration to environment or use ConfigMap as file-mount into a K8S pod
effort: 10
readiness: 3
category: env-config
tags:
- value: env-config
patterns:
- value: .AddJsonFile(
