name: java-jconfig.yaml
filetype: (jsp$|java$)
target: line echo name: jconfig
filetype: (jsp$|java$)
type: regex
defaultpattern: ^.*import(\s*|=)%s.*$
advice: Consult 3rd party documentation
category: jconfig
tags:
- value: jconfig
patterns:
- value: jconfig
