name: java-commons-configuration.yaml
filetype: (jsp$|java$)
target: line echo name: commons-configuration
filetype: (jsp$|java$)
type: regex
defaultpattern: ^.*import(\s*|=)%s.*$
advice: Consult 3rd party documentation
category: commons-configuration
tags:
- value: commons-configuration
patterns:
- value: commons-configuration
