name: weblogic-cluster-config
filetype: conf$
target: line
type: regex
defaultpattern: "^%s.*"
category: wlcluster
advice: weblogic clusters cannot run in K8S
effort: 1
readiness: 0
tags:
  - value: api
  - value: wlcluster
patterns:
  #--- cluster property
  - value: WebLogicCluster
