name: xml-ehcache-Config
filetype: xml$
target: file
type: contains
category: cache
advice: Consult 3rd party documentation
effort: 50
readiness: 10
tags:
- value: cache
- value: ehcache
patterns:
- value: ehcache.xml
## amq:broker
