name: Go

on:
  push:
    branches: [ master, build ]
  pull_request:
    branches: [ master ]

jobs:

#  buildWL:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#
#    - name: Check out code into the Go module directory
#      uses: actions/checkout@master
#
#    - name: install go-bindata
#      run: sudo apt update && sudo apt install -y go-bindata
#
#    - name: install windows compilers
#      run: sudo apt update && sudo apt install -y gcc-multilib && sudo apt install -y gcc-mingw-w64
#
#    - name: Build
#      run: ./build-Local.sh WL
#
#    - name: Upload artifacts
#      uses: actions/upload-artifact@master
#      with:
#        name: buildFiles
#        path: csa-app/exe

  buildOnMacos:
    name: Build on macos
    runs-on: macos-12
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Setup Go
      uses: actions/setup-go@master
      with:
        check-latest: true

    - name: install go-bindata
      run: brew update && brew install go-bindata

    - name: Build
      run: ./build-Local.sh O

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: buildMacosFiles
        path: csa-app/exe

