name: Go

on:
  push:
    branches: [ master, build-private-preview-release ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt install -y nodejs npm golang go-bindata musl-tools gcc-mingw-w64 build-essential

      - name: Install goreleaser
        run: sudo snap install goreleaser --classic

      - name: Build
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: buildFiles
          path: csa-app/dist

  buildOnMacos:
    name: Build on macos
    runs-on: macos-13
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      # macos-12 runner seems old go@1.17 make go-bindata install fail
      - name: install go-bindata
        run: brew install go-bindata

      - name: Build
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: buildMacFiles
          path: csa-app/dist