name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt install go-bindata mingw-w64
      
    - name: Build
      run: ./build-Local.sh OWL
    
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: buildFiles
        path: csa-app/exe

