name: Go

on:
  push:
    branches: [ add-azure-spring-app-rules ]
  pull_request:
    branches: [ add-azure-spring-app-rules ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2


    - name: Build
      run: ./build-Local.sh OWL
    
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: buildFiles
        path: csa-app/exe

